### ISSUE TITLE
sayHi returning error

### ISSUE THREAD

**Issue by TimeSmash** [learn-co-curriculum/prototypal-oo-js-object-oriented-object-methods-lab#3]
I'm not sure why, but the code here returns an error 
```
function BoardMember(name,homeState,training){
    this.name = name
    this.homeState = homeState
    this.training = training
}

BoardMember.prototype.sayHi= function(){
    return `Hi, my name is ${name}. I am from ${homeState}, and I was trained in ${training}.`
} 
``` 
saying homeState is not defined, which doesn't make a ton of sense seeing as how the other variables work.

**Comment by sgharms** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab.

The issue here appears to be with your own code.

Use the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature, where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can help you figure it out. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
